function cuedamount=defineCuedUnits(cued_success_Response)

cuedamount=( cued_success_Response.glmcoef_index8+...
                cued_success_Response.glmcoef_index9+...
                cued_success_Response.glmcoef_index10+...
                cued_success_Response.glmcoef_index11+...
                cued_success_Response.glmcoef_index12+...
                cued_success_Response.glmcoef_index13+...
                cued_success_Response.glmcoef_index14+...
                cued_success_Response.glmcoef_index15+...
                cued_success_Response.glmcoef_index16+...
                cued_success_Response.glmcoef_index17+...
                cued_success_Response.glmcoef_index18+...
                cued_success_Response.glmcoef_index19+...
                cued_success_Response.glmcoef_index20+...
                cued_success_Response.glmcoef_index21+...
                cued_success_Response.glmcoef_index22+...
                cued_success_Response.glmcoef_index23+...
                cued_success_Response.glmcoef_index24+...
                cued_success_Response.glmcoef_index25+...
                cued_success_Response.glmcoef_index26+...
                cued_success_Response.glmcoef_index27+...
                cued_success_Response.glmcoef_index28+...
                cued_success_Response.glmcoef_index29+...
                cued_success_Response.glmcoef_index30+...
                cued_success_Response.glmcoef_index31+...
                cued_success_Response.glmcoef_index32+...
                cued_success_Response.glmcoef_index33+...
                cued_success_Response.glmcoef_index34+...
                cued_success_Response.glmcoef_index35+...
                cued_success_Response.glmcoef_index36+...
                cued_success_Response.glmcoef_index37+...
                cued_success_Response.glmcoef_index38+...
                cued_success_Response.glmcoef_index39+...
                cued_success_Response.glmcoef_index40)/33 - ...
               (cued_success_Response.glmcoef_index1+...
                cued_success_Response.glmcoef_index2+...
                cued_success_Response.glmcoef_index3+...
                cued_success_Response.glmcoef_index4+...
                cued_success_Response.glmcoef_index5+...
                cued_success_Response.glmcoef_index6+...
                cued_success_Response.glmcoef_index7)/7;

figure(); histogram(cuedamount,100);

end